### ISSUE TITLE
Application Error on page load

### ISSUE THREAD

**Issue by Protonus** [oliverzheng/pandorasongs#2]
When accessing this URL:
http://pandorasongs.oliverzheng.com/ 

I get the following error:

>Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail

Not sure how long it's been like this, didn't see any other issues reported, figured I'd start here (also sending you an email).

**Comment by oliverzheng** [comment]
Hi @Protonus. The app runs on the free tier of Heroku's hosting service, which has a monthly quota. It looks like it used up its March quota already. Come back in April and it should work again.
